# Generated by Django 4.1.3 on 2022-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Upcoming', 'Upcoming'), ('Graded', 'Graded')], default='Open', max_length=25)),
            ],
        ),
    ]
